FROM node:alpine

WORKDIR /app

COPY package.json .
RUN npm install

COPY . .

# additional steps because docker run on root linux system
RUN chown -R node /app/node_modules
USER node

CMD [ "npm", "run", "start" ]